const AnalyticsDataActionTypes = {
  FETCH_ANALYTICSDATA_START: "FETCH_ANALYTICSDATA_START",
  FETCH_ANALYTICSDATA_SUCCESS: "FETCH_ANALYTICSDATA_SUCCESS",
  FETCH_ANALYTICSDATA_FAILURE: "FETCH_ANALYTICSDATA_FAILURE"
};

export default AnalyticsDataActionTypes;
