const TranscriptionsActionTypes = {
  FETCH_TRANSCRIPTIONS_START: "FETCH_TRANSCRIPTIONS_START",
  FETCH_TRANSCRIPTIONS_SUCCESS: "FETCH_TRANSCRIPTIONS_SUCCESS",
  FETCH_TRANSCRIPTIONS_FAILURE: "FETCH_TRANSCRIPTIONS_FAILURE"
};

export default TranscriptionsActionTypes;
