export const languages = {
  "Arabic (United Arab Emirates)": "ar-AE",
  "Arabic (Bahrain)": "ar-BH",
  "Arabic (Algeria)": "ar-DZ",
  "Arabic (Egypt)": "ar-EG",
  "Arabic (Israel)": "ar-IL",
  "Arabic (Iraq)": "ar-IQ",
  "Arabic (Jordan)": "ar-JO",
  "Arabic (Kuwait)": "ar-KW",
  "Arabic (Lebanon)": "ar-LB",
  "Arabic (Morocco)": "ar-MA",
  "Arabic (Oman)": "ar-OM",
  "Arabic (State of Palestine)": "ar-PS",
  "Arabic (Qatar)": "ar-QA",
  "Arabic (Saudi Arabia)": "ar-SA",
  "Arabic (Tunisia)": "ar-TN",
  "German (Germany)": "de-DE",
  "English (Australia)": "en-AU",
  "English (Canada)": "en-CA",
  "English (United Kingdom)": "en-GB",
  "English (Ghana)": "en-GH",
  "English (Ireland)": "en-IE",
  "English (India)": "en-IN",
  "English (Kenya)": "en-KE",
  "English (Nigeria)": "en-NG",
  "English (New Zealand)": "en-NZ",
  "English (Philippines)": "en-PH",
  "English (Singapore)": "en-SG",
  "English (Tanzania)": "en-TZ",
  "English (United States)": "en-US",
  "English (South Africa)": "en-ZA",
  "Spanish (Argentina)": "es-AR",
  "Spanish (Bolivia)": "es-BO",
  "Spanish (Chile)": "es-CL",
  "Spanish (Colombia)": "es-CO",
  "Spanish (Costa Rica)": "es-CR",
  "Spanish (Dominican Republic)": "es-DO",
  "Spanish (Ecuador)": "es-EC",
  "Spanish (Spain)": "es-ES",
  "Spanish (Guatemala)": "es-GT",
  "Spanish (Honduras)": "es-HN",
  "Spanish (Mexico)": "es-MX",
  "Spanish (Nicaragua)": "es-NI",
  "Spanish (Panama)": "es-PA",
  "Spanish (Peru)": "es-PE",
  "Spanish (Puerto Rico)": "es-PR",
  "Spanish (Paraguay)": "es-PY",
  "Spanish (El Salvador)": "es-SV",
  "Spanish (United States)": "es-US",
  "Spanish (Uruguay)": "es-UY",
  "Spanish (Venezuela)": "es-VE",
  "French (Canada)": "fr-CA",
  "French (France)": "fr-FR",
  "Italian (Italy)": "it-IT",
  "Japanese (Japan)": "ja-JP",
  "Korean (South Korea)": "ko-KR",
  "Dutch (Netherlands)": "nl-NL",
  "Dutch (Belgium)": "nl-BE",
  "Polish (Poland)": "pl-PL",
  "Portuguese (Brazil)": "pt-BR",
  "Russian (Russia)": "ru-RU",
  "Thai (Thailand)": "th-TH",
  "Turkish (Turkey)": "tr-TR",
  "Chinese, Mandarin (Simplified, China)": "zh (cmn-hans-cn)",
  "Chinese, Mandarin (Simplified, Hong Kong)": "zh-HK",
  "Chinese, Mandarin (Simplified, Taiwan)": "zh-TW (cmn-hans-tw)",
  "Bulgarian (Bulgaria)": "bg-BG",
  "Catalan (Spain)": "ca-ES",
  "Czech (Czech Republic)": "cs-CZ",
  "Danish (Denmark)": "da-DK",
  "Greek (Greece)": "el-GR",
  "Finnish (Finland)": "fi-FI",
  "Hebrew (Israel)": "he-IL",
  "Hindi (India)": "hi-IN",
  "Croatian (Croatia)": "hr-HR",
  "Hungarian (Hungary)": "hu-HU",
  "Indonesian (Indonesia)": "id-ID",
  "Lithuanian (Lithuania)": "lt-LT",
  "Latvian (Latvia)": "lv-LV",
  "Norwegian Bokm\u00e5l (Norway)": "nb-NO",
  "Portuguese (Portugal)": "pt-PT",
  "Romanian (Romania)": "ro-RO",
  "Slovak (Slovakia)": "sk-SK",
  "Slovenian (Slovenia)": "sl-SI",
  "Serbian (Serbia)": "sr-RS",
  "Swedish (Sweden)": "sv-SE",
  "Ukrainian (Ukraine)": "uk-UA",
  "Vietnamese (Vietnam)": "vi-VN",
  "Afrikaans (South Africa)": "af-ZA",
  "Amharic (Ethiopia)": "am-ET",
  "Azerbaijani (Azerbaijan)": "az-AZ",
  "Bengali (Bangladesh)": "bn-BD",
  "Bengali (India)": "bn-IN",
  "Estonian (Estonia)": "et-EE",
  "Basque (Spain)": "eu-ES",
  "Persian (Iran)": "fa-IR",
  "Filipino (Philippines)": "fil-PH",
  "Galician (Spain)": "gl-ES",
  "Gujarati (India)": "gu-IN",
  "Armenian (Armenia)": "hy-AM",
  "Icelandic (Iceland)": "is-IS",
  "Javanese (Indonesia)": "jv-ID",
  "Georgian (Georgia)": "ka-GE",
  "Khmer (Cambodia)": "km-KH",
  "Kannada (India)": "kn-IN",
  "Lao (Laos)": "lo-LA",
  "Macedonian (North Macedonia)": "mk-MK",
  "Malayalam (India)": "ml-IN",
  "Mongolian (Mongolia)": "mn-MN",
  "Marathi (India)": "mr-IN",
  "Malay (Malaysia)": "ms-MY",
  "Burmese (Myanmar)": "my-MM",
  "Nepali (Nepal)": "ne-NP",
  "Punjabi (Gurmukhi, India)": "pa-guru-IN",
  "Sinhala (Sri Lanka)": "si-LK",
  "Albanian (Albania)": "sq-AL",
  "Sundanese (Indonesia)": "su-ID",
  "Swahili (Kenya)": "sw-KE",
  "Swahili (Tanzania)": "sw-TZ",
  "Tamil (India)": "ta-IN",
  "Tamil (Sri Lanka)": "ta-LK",
  "Tamil (Malaysia)": "ta-MY",
  "Tamil (Singapore)": "ta-SG",
  "Telugu (India)": "te-IN",
  "Urdu (India)": "ur-IN",
  "Urdu (Pakistan)": "ur-PK",
  "Uzbek (Uzbekistan)": "uz-UZ",
  "Chinese, Cantonese (Traditional, Hong Kong)": "yue-Hant-HK",
  "Zulu (South Africa)": "zu-ZA",
};
export const contentClasifficationCodes = ["en"];
export const syntacticAnalysisCodes = [
  "zh",
  "zh-Hant",
  "en",
  "fr",
  "de",
  "it",
  "ja",
  "ko",
  "pt",
  "ru",
  "es",
];
export const entityAnalysisCodes = [
  "zh",
  "zh-Hant",
  "en",
  "fr",
  "de",
  "it",
  "ja",
  "ko",
  "pt",
  "ru",
  "es",
];
export const sentimentAnalysisCodes = [
  "zh",
  "zh-Hant",
  "en",
  "fr",
  "de",
  "it",
  "ja",
  "ko",
  "pt",
  "ru",
  "es",
];
export const entitySentimentAnalysisCodes = ["en", "ja", "es"];

export const keywordsCodes = [
  "bg",
  "cs",
  "da",
  "de",
  "el",
  "en",
  "es",
  "fi",
  "fr",
  "ga",
  "hr",
  "hu",
  "id",
  "it",
  "lt",
  "lv",
  "nl",
  "no",
  "pl",
  "pt",
  "ro",
  "ru",
  "sk",
  "sv",
  "tr",
  "uk",
];
