const CustomerMetadataActionTypes = {
  FETCH_CUSTOMER_METADATA_START: "FETCH_CUSTOMER_METADATA_START",
  FETCH_CUSTOMER_METADATA_SUCCESS: "FETCH_CUSTOMER_METADATA_SUCCESS",
  FETCH_CUSTOMER_METADATA_FAILURE: "FETCH_CUSTOMER_METADATA_FAILURE",
};

export default CustomerMetadataActionTypes;
