const NotificationsActionTypes = {
  FETCH_NOTIFICATIONS_BY_STATUS_START: "FETCH_NOTIFICATIONS_BY_STATUS_START",
  FETCH_NOTIFICATIONS_BY_STATUS_SUCCESS:
    "FETCH_NOTIFICATIONS_BY_STATUS_SUCCESS",
  FETCH_NOTIFICATIONS_BY_STATUS_FAILURE:
    "FETCH_NOTIFICATIONS_BY_STATUS_FAILURE",
  FETCH_NOTIFICATIONS_BY_DATE_START: "FETCH_NOTIFICATIONS_BY_DATE_START",
  FETCH_NOTIFICATIONS_BY_DATE_SUCCESS: "FETCH_NOTIFICATIONS_BY_DATE_SUCCES",
  FETCH_NOTIFICATIONS_BY_DATE_FAILURE: "FETCH_NOTIFICATIONS_BY_DATE_FAILURE",
  CHANGE_NOTIFICATIONS_STATUS_START: "CHANGE_NOTIFICATIONS_STATUS",
  CHANGE_NOTIFICATIONS_STATUS_SUCCESS: "CHANGE_NOTIFICATIONS_STATUS_SUCCESS",
  CHANGE_NOTIFICATIONS_STATUS_FAILURE: "CHANGE_NOTIFICATIONS_STATUS_FAILURE",
};

export default NotificationsActionTypes;
